[env:airtrack-ride-firmware-esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

board_build.flash_mode = dio
board_build.filesystem = littlefs

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps =
	olikraus/U8g2@
	adafruit/Adafruit BME280 Library@^2.3.0
	adafruit/Adafruit Unified Sensor@^1.1.15
